# Generated by Django 5.1.8 on 2025-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data_refer', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('kw', models.IntegerField()),
            ],
        ),
    ]
